plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = "${project.archives_base_name}-${project.branch_name}-${stonecutter.current.version}"
}

repositories {
	maven {
		name = 'Terraformers'
		url = 'https://maven.terraformersmc.com/releases/'
	}
	maven {
		name = 'isXander'
		url = 'https://maven.isxander.dev/releases/'
	}
	maven {
		name = 'shedaniel'
		url = 'https://maven.shedaniel.me/'
	}
	maven {
		name = 'Modrinth'
		url = 'https://api.modrinth.com/maven'
		content {
			includeGroup 'maven.modrinth'
		}
	}
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${stonecutter.current.version}"
	implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	implementation "com.terraformersmc:modmenu:${project.mod_menu_version}"

	compileOnly "dev.isxander:yet-another-config-lib:${project.yacl_version}"
	localRuntime "dev.isxander:yet-another-config-lib:${project.yacl_version}"

	compileOnly "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}"
	localRuntime "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}"

	compileOnly "maven.modrinth:midnightlib:${project.midnightlib_version}"
	localRuntime "maven.modrinth:midnightlib:${project.midnightlib_version}"

	if (project.fcap_version) {
		compileOnly "maven.modrinth:forge-config-api-port:${project.fcap_version}"
		localRuntime "maven.modrinth:forge-config-api-port:${project.fcap_version}"
		compileOnly "com.electronwill.night-config:core:${project.night_config_version}"
	}
}

processResources {
	def version = project.version
	def minecraftDep = project.minecraft_dep
	def javaVersion = project.java_version
	inputs.property "version", version
	inputs.property "minecraftDep", minecraftDep
	inputs.property "javaVersion", javaVersion

	filesMatching("fabric.mod.json") {
		expand "version": version, "minecraftDep": minecraftDep, "javaVersion": javaVersion
	}

	filesMatching("configsearch.mixins.json") {
		expand "javaVersion": javaVersion
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = Integer.parseInt(project.java_version)
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.toVersion(project.java_version)
	targetCompatibility = JavaVersion.toVersion(project.java_version)
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from(rootProject.file("LICENSE")) {
		rename { "${it}_$projectName" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
