plugins {
	id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = "${project.archives_base_name}-${project.branch_name}-${stonecutter.current.version}"
}

repositories {
	maven {
		name = 'MinecraftForge'
		url = 'https://maven.minecraftforge.net/'
	}
	maven {
		name = 'shedaniel'
		url = 'https://maven.shedaniel.me/'
	}
	maven {
		name = 'CurseMaven'
		url = 'https://cursemaven.com'
		content {
			includeGroup 'curse.maven'
		}
	}
	mavenCentral()
}

def useOfficialRuntime = !stonecutter.current.version.startsWith('1.20')

minecraft {
	mappings channel: 'official', version: stonecutter.current.version

	if (useOfficialRuntime) {
		reobf = false
		copyIdeResources = true
	}

	runs {
		client {
			workingDirectory project.file('run')
			property 'forge.logging.markers', 'REGISTRIES'
			property 'forge.logging.console.level', 'debug'
			mods {
				configsearch {
					source sourceSets.main
				}
			}
		}
	}
}

if (useOfficialRuntime) {
	sourceSets.each {
		def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
		it.output.resourcesDir = dir
		it.java.destinationDirectory = dir
	}
}

dependencies {
	minecraft "net.minecraftforge:forge:${stonecutter.current.version}-${project.forge_version}"

	if (project.hasProperty('cloth_config_version') && project.cloth_config_version) {
		compileOnly "me.shedaniel.cloth:cloth-config-forge:${project.cloth_config_version}"
		runtimeOnly "me.shedaniel.cloth:cloth-config-forge:${project.cloth_config_version}"
	}

	if (project.hasProperty('configured_file_id') && project.configured_file_id) {
		compileOnly "curse.maven:configured-457570:${project.configured_file_id}"
		if (useOfficialRuntime) {
			runtimeOnly "curse.maven:configured-457570:${project.configured_file_id}"
		}
	}

	if (project.hasProperty('night_config_version') && project.night_config_version) {
		compileOnly "com.electronwill.night-config:core:${project.night_config_version}"
	}
}

processResources {
	def version = project.version
	def minecraftDep = project.minecraft_dep
	def javaVersion = project.java_version
	def forgeVersionRange = project.forge_version_range
	def resourcePackFormat = project.resource_pack_format
	inputs.property 'version', version
	inputs.property 'minecraftDep', minecraftDep
	inputs.property 'javaVersion', javaVersion
	inputs.property 'forgeVersionRange', forgeVersionRange
	inputs.property 'resourcePackFormat', resourcePackFormat

	filesMatching('META-INF/mods.toml') {
		expand 'version': version, 'minecraftDep': minecraftDep, 'javaVersion': javaVersion, 'forgeVersionRange': forgeVersionRange
	}
	filesMatching('pack.mcmeta') {
		expand 'resourcePackFormat': resourcePackFormat
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = Integer.parseInt(project.java_version)
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.toVersion(project.java_version)
	targetCompatibility = JavaVersion.toVersion(project.java_version)
}

jar {
	def projectName = project.name
	inputs.property 'projectName', projectName

	from(rootProject.file('LICENSE')) {
		rename { "${it}_$projectName" }
	}
}

if (!useOfficialRuntime) {
	reobf {
		jar {}
	}

	tasks.named('jar').configure {
		finalizedBy tasks.named('reobfJar')
	}
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			artifact jar
		}
	}

	repositories {
	}
}
