org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

modName=Config Search
modId=configsearch
modVersion=1.0.0
mavenGroup=dev.finndog.configsearch

minecraftVersion=26.2
loaderVersion=0.19.3
loomVersion=1.17.13

fabricApiVersion=0.154.1+26.2
modMenuVersion=20.0.0-beta.4
yaclVersion=3.9.5+26.2-fabric
clothConfigVersion=26.2.155
midnightlibVersion=1.9.3+26.2-fabric
