org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false
org.gradle.configuration-cache=false
dev.kikugie.stonecutter.hard_mode=true

modName=Config Search
modId=configsearch
modVersion=1.0.0
mavenGroup=dev.finndog.configsearch

moddevVersion=2.0.142

branchName=neoforge
publishBranch=neoforge

modrinthProjectId=wsGFU1GE
curseforgeProjectId=1603654
modrinthProjectSlug=config-search
curseforgeProjectSlug=config-search
publishDisplayPrefix=Config Search
publishDisplaySuffix=

discordEmbedColor=#57f287
discordAvatarUrl=https://media.forgecdn.net/avatars/thumbnails/1909/867/256/256/639191948711121606.png
discordThumbnailUrl=https://media.forgecdn.net/avatars/thumbnails/1909/867/256/256/639191948711121606.png
discordBannerUrl=
discordPing=true

releaseType=minor
alphaBuild=false
minecraftVersion=26.2
publishMcStart=26.2
publishMcEnd=26.2
