pluginManagement {
	repositories {
		maven {
			name = 'MinecraftForge'
			url = 'https://maven.minecraftforge.net/'
		}
		maven {
			name = 'KikuGie'
			url = 'https://maven.kikugie.dev/releases'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'dev.kikugie.stonecutter' version '0.7.11'
}

stonecutter {
	shared {
		vcsVersion = '1.21.1'
		version('1.20.1', '1.20.1').buildscript('build.gradle')
		version('1.21.1', '1.21.1').buildscript('build.gradle')
	}
	create rootProject
}

rootProject.name = 'configsearch'
