javaVersion=25
minecraftVersion=26.1.2
publishMcStart=26.1.2
publishMcEnd=26.1.2
minecraftDep=[26.1.2,26.2)
neoForgeVersion=26.1.2.84
neoForgeVersionRange=[26.1,26.2)
yaclVersion=3.9.6+26.1-neoforge
clothConfigVersion=26.1.154
midnightlibVersion=1.9.3+26.1-neoforge
nightConfigVersion=3.8.4
configuredFileId=7943180
