javaVersion=21
minecraftVersion=1.21.11
publishMcStart=1.21.11
publishMcEnd=1.21.11
minecraftDep=~1.21.11
fabricApiVersion=0.141.4+1.21.11
modMenuVersion=17.0.0
yaclVersion=3.8.1+1.21.11-fabric
clothConfigVersion=21.11.153
midnightlibVersion=1.9.3+1.21.11-fabric
fcapVersion=uXrWPsCu
nightConfigVersion=3.8.3
configuredFileId=7530374
