javaVersion=21
minecraftVersion=1.21.1
publishMcStart=1.21.1
publishMcEnd=1.21.1
minecraftDep=[1.21.1,1.21.2)
neoForgeVersion=21.1.240
neoForgeVersionRange=[21.1,21.2)
parchmentMinecraftVersion=1.21.1
parchmentMappingsVersion=2024.11.17
yaclVersion=3.8.1+1.21.1-neoforge
clothConfigVersion=15.0.140
midnightlibVersion=1.9.3+1.21.1-neoforge
nightConfigVersion=3.8.0
configuredFileId=7276577
